name: music_filter
description: A small app to play a bunch of music and delete the ones I don't like

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.0.1+1

environment:
  sdk: '>=3.0.3 <4.0.0'

# Define version strings here
isar_version: &isar_version ^3.1.0

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.9.0              # Meta class information (e.g. protected annotations)
  async: ^2.11.0            # Extensions for async operations
  collection: ^1.17.0       # More operations on collections
  intl: ^0.18.0             # Localization
  provider: ^6.0.0          # Provider/Notifier for application-wide state
  cupertino_icons: ^1.0.2   # CupertinoIcons class for iOS style icons.
  permission_handler: ^10.3.0   # Check/request for permissions on Android/iOS
  shared_preferences: ^2.1.0    # SharedPreferences / NSUserDefaults wrapper
  pref: ^2.7.0                  # Preferences screen
  path: ^1.8.3                  # Path manipulation (e.g. os.path.join like)
  path_provider: ^2.0.15        # Paths for storage
  file_picker: ^5.3.2           # File/Folder picker
  isar: *isar_version               # Local NoSQL DB
  isar_flutter_libs: *isar_version  # contains Isar Core
  flutter_media_metadata: ^1.0.0+1  # Fetch audio tags from File

dev_dependencies:
  flutter_test:
    sdk: flutter

  # For generating isar schemas, run:
  # flutter pub run build_runner build
  isar_generator: *isar_version
  build_runner: ^2.4.4

  # Configure lints in `analysis_options.yaml`
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
